### ISSUE TITLE
Function composition

### ISSUE THREAD

**Issue by poteto** [rtablada/ember-compose-action-helper#1]
As it is, I think the addon name might be a little misleading, as it isn't actually composing functions but invoking them in sequence. We could update the helper to do something along these lines:

``` js
import Ember from 'ember';

export function compose([f, g]) {
  return function(...args) {
    return f(g(...args));
  };
}

export default Ember.Helper.helper(compose);
```

**Comment by rtablada** [comment]
Agreed, I also think there is a place for sequencing actions, promise aware composition, grouping, etc.

**Comment by poteto** [comment]
Made a little twiddle https://ember-twiddle.com/aa6660ffdccc0ee7a2d4?openFiles=application.controller.js%2Cfoo-bar.template.hbs

**Comment by rtablada** [comment]
Hmm... Yeah that does make things a bit awkward in terms of API...

**Comment by rtablada** [comment]
I have implemented a new `compose` helper:

https://github.com/rtablada/ember-compose-action-helper#composing

**Comment by poteto** [comment]
:+1:
